# Generated by Django 2.2 on 2021-01-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rene_app', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.TextField()),
                ('resource', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solution_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_posted', to='rene_app.Question')),
            ],
        ),
    ]
