# Generated by Django 2.2 on 2021-01-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rene_app', '0003_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.CharField(choices=[('algebra', 'ALGEBRA'), ('precalculus', 'PRECALCULUS'), ('calculus', 'CALCULUS'), ('calculus2', ' CALCULUS2')], default='algebra', max_length=255),
        ),
    ]
