# Generated by Django 2.2 on 2021-01-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rene_app', '0004_auto_20210125_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='agrees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution',
            field=models.BooleanField(default=False),
        ),
    ]
